[package]
name = "markdown-composer"
description = "A library for composing markdown documents."
version = "0.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/SirWindfield/markdown-composer"
authors = ["Sven Lechner <SirWindfield@users.noreply.github.com>"]
edition = "2018"
